AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test/dummy/config/**/*'
    - 'test/dummy/bin/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - '*.gemspec'
    - 'Gemfile*'
    - 'bin/**/*'

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120
